Hide gb-custom-select list on item select
groupby/searchandiser-ui pull request #196
Opened 2017-05-04 20:00 UTC by ashima-g

Remove hover selectors and hide the list using the `visibility` property
instead of the `display` property to allow a slight delay for the click event
to be registered.

http://koen.kivits.com/articles/pure-css-menu/

2017-05-04 21:19 UTC, Vic-Dev requested changes
Looks good. Tomorrow we will set you up to be able to attemp this fix against the client's site, just to make sure it fixes the problem for them.

2017-05-05 20:39 UTC, jmbtutor commented
@Vic-Dev: Changed the implementation to be more robust by using a flag and class.

2017-05-08 16:11 UTC, Vic-Dev requested changes
Hey looks good. Please make that small fix, and rebase off develop if needed :)

2017-05-08 16:11 UTC, Vic-Dev commented on src/tags/select/gb-select.ts
>    focusElement(e: Event & { preventUpdate: boolean }) {
Please remove this parameter (it's not being used) :)

2017-05-08 19:13 UTC, ashima-g commented
The changes to gb-select have been made.

2017-05-09 15:45 UTC, Vic-Dev approved these changes

2017-05-09 15:47 UTC, merged